# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e297b4ba1cc7da703976f0d1747d1eb649bf8991e9ba1df7081d3cc84ee7320f48c535e2ce6f73c4887d8e6c4035637632e371aefd3ecd59292ac9514ed676b

test:
  secret_key_base: 41aff17a53e3d2e64fc07b476b4d77435463a1462eea5899a5c21e5dff38f8b108b4de2e4c77ce6073d52b5bc2f58e964bde64d0f630f9e8227d9952aad9c0bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
